[project]
name = "blender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databpy>=0.7.0",
    "geonamescache>=3.0.1",
    "geopandas>=1.1.4",
    "h5py>=3.16.0",
    "matplotlib>=3.11.0",
    "unyt>=3.1.0",
    "yt>=4.4.2",
]
